In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
#import graphviz
from sklearn import ensemble , preprocessing , metrics , svm , tree , linear_model
from sklearn.neural_network import MLPClassifier
from keras.utils import np_utils
from keras.models import Sequential
from keras.layers import Dense, Activation ,Dropout
from keras.optimizers import RMSprop ,Adam

Using TensorFlow backend.

## import train test data

In [3]:
data = pd.read_csv('C:\\Users\\USER\\github\\E.sun_conpetition\\data_set\\clean_data.csv')

In [4]:
data.head()

,Unnamed: 0,building_id,building_material,city,txn_dt,total_floor,building_type,building_use,building_complete_dt,parking_way,...,XIV_500,XIV_index_500,XIV_1000,XIV_index_1000,XIV_5000,XIV_index_5000,XIV_10000,XIV_index_10000,XIV_MIN,total_price
0,0,e3mMIMR3JJqCaXz1,8,21,18674,4,3,2,6271,2,...,58,1,157,1,2483,1,6011,1,34.469803,6.476038e+05
1,1,LgwzgklNvy4QCtq5,8,7,18800,5,1,2,7885,2,...,28,1,115,1,15872,1,32221,1,40.073573,3.321452e+06
2,2,ucIR2NLLsC3T650L,8,7,19289,4,1,2,6028,2,...,78,1,212,1,15760,1,32228,1,54.462081,9.570885e+06
3,3,jre1pJhcQj91Kdky,8,21,20385,24,0,2,18325,0,...,20,1,125,1,2568,1,7271,1,99.628966,1.421501e+07
4,4,rQpYpY9nRG7X5mmr,1,21,20657,2,4,2,6880,2,...,18,1,47,1,2587,1,7442,1,124.131236,7.627120e+05

In [11]:
data = data.iloc[:,1:]

### 將columns名稱儲存

In [12]:
columnslist = data.columns.tolist()

## 儲存 building_id 來做為辨識

In [14]:
buildid = data[columnslist[0]]

In [15]:
buildid[:5]

0    e3mMIMR3JJqCaXz1
1    LgwzgklNvy4QCtq5
2    ucIR2NLLsC3T650L
3    jre1pJhcQj91Kdky
4    rQpYpY9nRG7X5mmr
Name: building_id, dtype: object

## 將預測值 存取成train_y

In [16]:
train_y = data[columnslist[-1]]

In [17]:
train_y[:5]

0    6.476038e+05
1    3.321452e+06
2    9.570885e+06
3    1.421501e+07
4    7.627120e+05
Name: total_price, dtype: float64

## 將類別資料找出  並且以one_hot_encoding來處理

## 類別特徵分離出來

In [18]:
columnslist

['building_id',
 'building_material',
 'city',
 'txn_dt',
 'total_floor',
 'building_type',
 'building_use',
 'building_complete_dt',
 'parking_way',
 'parking_area',
 'parking_price',
 'txn_floor',
 'land_area',
 'building_area',
 'town',
 'lat',
 'lon',
 'village_income_median',
 'town_population',
 'town_area',
 'town_population_density',
 'doc_Rate',
 'master_rate',
 'bachelor_rate',
 'jobschool_rate',
 'highschool_rate',
 'junior_rate',
 'elementary_rate',
 'born_rate',
 'death_date',
 'marriage_rate',
 'divorce_rate',
 'village',
 'N_50',
 'N_500',
 'N_1000',
 'N_5000',
 'N_10000',
 'I_10',
 'I_50',
 'I_index_50',
 'I_100',
 'I_250',
 'I_500',
 'I_index_500',
 'I_1000',
 'I_index_1000',
 'I_5000',
 'I_index_5000',
 'I_10000',
 'I_index_10000',
 'I_MIN',
 'II_10',
 'II_50',
 'II_index_50',
 'II_100',
 'II_250',
 'II_500',
 'II_index_500',
 'II_1000',
 'II_index_1000',
 'II_5000',
 'II_index_5000',
 'II_10000',
 'II_index_10000',
 'II_MIN',
 'III_10',
 'III_50',
 'III_index_50',
 'III_100',
 'III_250',
 'III_500',
 'III_index_500',
 'III_1000',
 'III_index_1000',
 'III_5000',
 'III_index_5000',
 'III_10000',
 'III_index_10000',
 'III_MIN',
 'IV_10',
 'IV_50',
 'IV_index_50',
 'IV_100',
 'IV_250',
 'IV_500',
 'IV_index_500',
 'IV_1000',
 'IV_index_1000',
 'IV_5000',
 'IV_index_5000',
 'IV_10000',
 'IV_index_10000',
 'IV_MIN',
 'V_10',
 'V_50',
 'V_index_50',
 'V_100',
 'V_250',
 'V_500',
 'V_index_500',
 'V_1000',
 'V_index_1000',
 'V_5000',
 'V_index_5000',
 'V_10000',
 'V_index_10000',
 'V_MIN',
 'VI_10',
 'VI_50',
 'VI_index_50',
 'VI_100',
 'VI_250',
 'VI_500',
 'VI_index_500',
 'VI_1000',
 'VI_index_1000',
 'VI_5000',
 'VI_index_5000',
 'VI_10000',
 'VI_index_10000',
 'VI_MIN',
 'VII_10',
 'VII_50',
 'VII_index_50',
 'VII_100',
 'VII_250',
 'VII_500',
 'VII_index_500',
 'VII_1000',
 'VII_index_1000',
 'VII_5000',
 'VII_index_5000',
 'VII_10000',
 'VII_index_10000',
 'VII_MIN',
 'VIII_10',
 'VIII_50',
 'VIII_index_50',
 'VIII_100',
 'VIII_250',
 'VIII_500',
 'VIII_index_500',
 'VIII_1000',
 'VIII_index_1000',
 'VIII_5000',
 'VIII_index_5000',
 'VIII_10000',
 'VIII_index_10000',
 'VIII_MIN',
 'IX_10',
 'IX_50',
 'IX_index_50',
 'IX_100',
 'IX_250',
 'IX_500',
 'IX_index_500',
 'IX_1000',
 'IX_index_1000',
 'IX_5000',
 'IX_index_5000',
 'IX_10000',
 'IX_index_10000',
 'IX_MIN',
 'X_10',
 'X_50',
 'X_index_50',
 'X_100',
 'X_250',
 'X_500',
 'X_index_500',
 'X_1000',
 'X_index_1000',
 'X_5000',
 'X_index_5000',
 'X_10000',
 'X_index_10000',
 'X_MIN',
 'XI_10',
 'XI_50',
 'XI_index_50',
 'XI_100',
 'XI_250',
 'XI_500',
 'XI_index_500',
 'XI_1000',
 'XI_index_1000',
 'XI_5000',
 'XI_index_5000',
 'XI_10000',
 'XI_index_10000',
 'XI_MIN',
 'XII_10',
 'XII_50',
 'XII_index_50',
 'XII_100',
 'XII_250',
 'XII_500',
 'XII_index_500',
 'XII_1000',
 'XII_index_1000',
 'XII_5000',
 'XII_index_5000',
 'XII_10000',
 'XII_index_10000',
 'XII_MIN',
 'XIII_10',
 'XIII_50',
 'XIII_index_50',
 'XIII_100',
 'XIII_250',
 'XIII_500',
 'XIII_index_500',
 'XIII_1000',
 'XIII_index_1000',
 'XIII_5000',
 'XIII_index_5000',
 'XIII_10000',
 'XIII_index_10000',
 'XIII_MIN',
 'XIV_10',
 'XIV_50',
 'XIV_index_50',
 'XIV_100',
 'XIV_250',
 'XIV_500',
 'XIV_index_500',
 'XIV_1000',
 'XIV_index_1000',
 'XIV_5000',
 'XIV_index_5000',
 'XIV_10000',
 'XIV_index_10000',
 'XIV_MIN',
 'total_price']

In [ ]:
list_dummy = []